@startuml
[*] --> Init
Init: Initialize
Start: Pump is running
Ready: Pump stopped
Manual: Check state
Init --> Ready
Init --> Manual : Check sensors error
Ready --> Start : Low pressure
Start --> Ready : High pressure
Start --> Manual : High temp SSR
Start --> Manual : High temp PUMP
Start --> Manual : Long time run
Start --> Manual : Check sensors error
Manual --> Ready : Confirmation
note on link
  Manual button
end note
@enduml